COUNTRY_CODES = {
    "Afghanistan": "AFG",
    "American Samoa": "ASM",
    "Australia": "AUS",
    "Austria": "AUT",
    "Bahamas": "BHS",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Belize": "BLZ",
    "Brazil": "BRA",
    "Brunei Darussalam": "BRN",
    "Canada": "CAN",
    "China": "CHN",
    "Colombia": "COL",
    "Costa Rica": "CRI",
    "Croatia": "HRV",
    "Cuba": "CUB",
    "Curacao": "CUW",
    "Czech Republic": "CZE",
    "Denmark": "DNK",
    "England": "GBR",
    "Finland": "FIN",
    "France": "FRA",
    "Germany": "GER",
    "Honduras": "HND",
    "Indonesia": "IDN",
    "Ireland": "IRL",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Kazakhstan": "KAZ",
    "Korea": "KOR",
    "Latvia": "LVA",
    "Lebanon": "LBN",
    "Lithuania": "LTU",
    "Mexico": "MEX",
    "Netherlands": "NLD",
    "Nicaragua": "NIC",
    "Nigeria": "NGA",
    "Northern Ireland": "GBR",
    "Norway": "NOR",
    "Panama": "PAN",
    "Paraguay": "PRY",
    "Philippines": "PHL",
    "Poland": "POL",
    "Russia": "RUS",
    "San Marino": "SMR",
    "Saudi Arabia": "SAU",
    "Scotland": "GBR",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "South Africa": "ZAF",
    "South Korea": "KOR",
    "South Wales": "GBR",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Taiwan": "TWN",
    "Tanzania": "TZA",
    "Ukraine": "UKR",
    "United Kingdom": "GBR",
    "Venezuela": "VEN",
    "Viet Nam": "VNM"
}
