COUNTRY_CODES = {
    "Afghanistan": "AFG",
    "American Samoa": "ASM",
    "Australia": "AUS",
    "Austria": "AUT",
    "Bahamas": "BHS",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Belize": "BLZ",
    "Brazil": "BRA",
    "Brunei Darussalam": "BRN",
    "Canada": "CAN",
    "China": "CHN",
    "Colombia": "COL",
    "Costa Rica": "CRI",
    "Croatia": "HRV",
    "Cuba": "CUB",
    "Curacao": "CUW",
    "Czech Republic": "CZE",
    "Denmark": "DNK",
    "England": "GBR",
    "Finland": "FIN",
    "France": "FRA",
    "Germany": "GER",
    "Honduras": "HND",
    "Indonesia": "IDN",
    "Ireland": "IRL",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Kazakhstan": "KAZ",
    "Korea": "KOR",
    "Latvia": "LVA",
    "Lebanon": "LBN",
    "Lithuania": "LTU",
    "Mexico": "MEX",
    "Netherlands": "NLD",
    "Nicaragua": "NIC",
    "Nigeria": "NGA",
    "Northern Ireland": "GBR",
    "Norway": "NOR",
    "Panama": "PAN",
    "Paraguay": "PRY",
    "Philippines": "PHL",
    "Poland": "POL",
    "Russia": "RUS",
    "San Marino": "SMR",
    "Saudi Arabia": "SAU",
    "Scotland": "GBR",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "South Africa": "ZAF",
    "South Korea": "KOR",
    "South Wales": "GBR",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Taiwan": "TWN",
    "Tanzania": "TZA",
    "Ukraine": "UKR",
    "United Kingdom": "GBR",
    "Venezuela": "VEN",
    "Viet Nam": "VNM"
}

TEAM_CODES = {
    "LAC": "Los Angeles Clippers",
    "DEN": "Denver Nuggets",
    "WAS": "Washington Wizards",
    "NYK": "New York Knickerbockers",
    "SAC": "Sacramento Kings",
    "DAL": "Dallas Mavericks",
    "BOS": "Boston Celtics",
    "CLE": "Cleveland Cavaliers",
    "HOU": "Houston Rockets",
    "PHX": "Pheonix Suns",
    "ORL": "Orlando Magic",
    "PHI": "Philadelphia 76ers",
    "MIA": "Miami Heat",
    "NOH": "New Orleans Hurricanes",
    "CHI": "Chicago Bulls",
    "UTA": "Utah Jazz",
    "DET": "Detroit Pistons",
    "IND": "Indiana Pacers",
    "CHA": "Charlotte Hornets",
    "NJN": "New Jersey Nets",
    "LAL": "Los Angeles Lakers",
    "MIN": "Minnesota Timberwolves",
    "MIL": "Milwaukee Bucks",
    "MEM": "Memphis Sounds",
    "ATL": "Atlanta Hawks",
    "POR": "Portland Trailblazers",
    "TOR": "Toronto Raptors"}
